// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/server/server.proto

package server

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceDataType int32

const (
	DeviceDataType_UNKNOWN         DeviceDataType = 0
	DeviceDataType_INSTALLED_APPS  DeviceDataType = 1
	DeviceDataType_OS_VERSION      DeviceDataType = 2
	DeviceDataType_OSQUERY_VERSION DeviceDataType = 3
)

// Enum value maps for DeviceDataType.
var (
	DeviceDataType_name = map[int32]string{
		0: "UNKNOWN",
		1: "INSTALLED_APPS",
		2: "OS_VERSION",
		3: "OSQUERY_VERSION",
	}
	DeviceDataType_value = map[string]int32{
		"UNKNOWN":         0,
		"INSTALLED_APPS":  1,
		"OS_VERSION":      2,
		"OSQUERY_VERSION": 3,
	}
)

func (x DeviceDataType) Enum() *DeviceDataType {
	p := new(DeviceDataType)
	*p = x
	return p
}

func (x DeviceDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_server_server_proto_enumTypes[0].Descriptor()
}

func (DeviceDataType) Type() protoreflect.EnumType {
	return &file_protos_server_server_proto_enumTypes[0]
}

func (x DeviceDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceDataType.Descriptor instead.
func (DeviceDataType) EnumDescriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{0}
}

// Message definitions will be added here
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_protos_server_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginRequest is the request for the Login method
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_protos_server_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type InstalledApps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*InstalledApps_App   `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledApps) Reset() {
	*x = InstalledApps{}
	mi := &file_protos_server_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledApps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledApps) ProtoMessage() {}

func (x *InstalledApps) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledApps.ProtoReflect.Descriptor instead.
func (*InstalledApps) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{2}
}

func (x *InstalledApps) GetApps() []*InstalledApps_App {
	if x != nil {
		return x.Apps
	}
	return nil
}

type OSVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSVersion) Reset() {
	*x = OSVersion{}
	mi := &file_protos_server_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSVersion) ProtoMessage() {}

func (x *OSVersion) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSVersion.ProtoReflect.Descriptor instead.
func (*OSVersion) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{3}
}

func (x *OSVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type OSQueryVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSQueryVersion) Reset() {
	*x = OSQueryVersion{}
	mi := &file_protos_server_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSQueryVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSQueryVersion) ProtoMessage() {}

func (x *OSQueryVersion) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSQueryVersion.ProtoReflect.Descriptor instead.
func (*OSQueryVersion) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{4}
}

func (x *OSQueryVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// DeviceDataRequest is the request for the SendDeviceData method
type DeviceDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DataRequestType DeviceDataType         `protobuf:"varint,1,opt,name=data_request_type,json=dataRequestType,proto3,enum=server.DeviceDataType" json:"data_request_type,omitempty"`
	InstalledApps   *InstalledApps         `protobuf:"bytes,2,opt,name=installed_apps,json=installedApps,proto3" json:"installed_apps,omitempty"`
	OsVersion       *OSVersion             `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsqueryVersion  *OSQueryVersion        `protobuf:"bytes,4,opt,name=osquery_version,json=osqueryVersion,proto3" json:"osquery_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceDataRequest) Reset() {
	*x = DeviceDataRequest{}
	mi := &file_protos_server_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDataRequest) ProtoMessage() {}

func (x *DeviceDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDataRequest.ProtoReflect.Descriptor instead.
func (*DeviceDataRequest) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceDataRequest) GetDataRequestType() DeviceDataType {
	if x != nil {
		return x.DataRequestType
	}
	return DeviceDataType_UNKNOWN
}

func (x *DeviceDataRequest) GetInstalledApps() *InstalledApps {
	if x != nil {
		return x.InstalledApps
	}
	return nil
}

func (x *DeviceDataRequest) GetOsVersion() *OSVersion {
	if x != nil {
		return x.OsVersion
	}
	return nil
}

func (x *DeviceDataRequest) GetOsqueryVersion() *OSQueryVersion {
	if x != nil {
		return x.OsqueryVersion
	}
	return nil
}

// LatestDataRequest is the request for the LatestData method
type LatestDataRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DataRequestTypes []DeviceDataType       `protobuf:"varint,2,rep,packed,name=data_request_types,json=dataRequestTypes,proto3,enum=server.DeviceDataType" json:"data_request_types,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LatestDataRequest) Reset() {
	*x = LatestDataRequest{}
	mi := &file_protos_server_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestDataRequest) ProtoMessage() {}

func (x *LatestDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestDataRequest.ProtoReflect.Descriptor instead.
func (*LatestDataRequest) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{6}
}

func (x *LatestDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LatestDataRequest) GetDataRequestTypes() []DeviceDataType {
	if x != nil {
		return x.DataRequestTypes
	}
	return nil
}

type LatestDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstalledApps  *InstalledApps         `protobuf:"bytes,1,opt,name=installed_apps,json=installedApps,proto3" json:"installed_apps,omitempty"`
	OsVersion      *OSVersion             `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsqueryVersion *OSQueryVersion        `protobuf:"bytes,3,opt,name=osquery_version,json=osqueryVersion,proto3" json:"osquery_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LatestDataResponse) Reset() {
	*x = LatestDataResponse{}
	mi := &file_protos_server_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestDataResponse) ProtoMessage() {}

func (x *LatestDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestDataResponse.ProtoReflect.Descriptor instead.
func (*LatestDataResponse) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{7}
}

func (x *LatestDataResponse) GetInstalledApps() *InstalledApps {
	if x != nil {
		return x.InstalledApps
	}
	return nil
}

func (x *LatestDataResponse) GetOsVersion() *OSVersion {
	if x != nil {
		return x.OsVersion
	}
	return nil
}

func (x *LatestDataResponse) GetOsqueryVersion() *OSQueryVersion {
	if x != nil {
		return x.OsqueryVersion
	}
	return nil
}

type InstalledApps_App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledApps_App) Reset() {
	*x = InstalledApps_App{}
	mi := &file_protos_server_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledApps_App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledApps_App) ProtoMessage() {}

func (x *InstalledApps_App) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledApps_App.ProtoReflect.Descriptor instead.
func (*InstalledApps_App) Descriptor() ([]byte, []int) {
	return file_protos_server_server_proto_rawDescGZIP(), []int{2, 0}
}

func (x *InstalledApps_App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledApps_App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_protos_server_server_proto protoreflect.FileDescriptor

const file_protos_server_server_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/server/server.proto\x12\x06server\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"T\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"s\n" +
	"\rInstalledApps\x12-\n" +
	"\x04apps\x18\x01 \x03(\v2\x19.server.InstalledApps.AppR\x04apps\x1a3\n" +
	"\x03App\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"%\n" +
	"\tOSVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"*\n" +
	"\x0eOSQueryVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x88\x02\n" +
	"\x11DeviceDataRequest\x12B\n" +
	"\x11data_request_type\x18\x01 \x01(\x0e2\x16.server.DeviceDataTypeR\x0fdataRequestType\x12<\n" +
	"\x0einstalled_apps\x18\x02 \x01(\v2\x15.server.InstalledAppsR\rinstalledApps\x120\n" +
	"\n" +
	"os_version\x18\x03 \x01(\v2\x11.server.OSVersionR\tosVersion\x12?\n" +
	"\x0fosquery_version\x18\x04 \x01(\v2\x16.server.OSQueryVersionR\x0eosqueryVersion\"r\n" +
	"\x11LatestDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12D\n" +
	"\x12data_request_types\x18\x02 \x03(\x0e2\x16.server.DeviceDataTypeR\x10dataRequestTypes\"\xc5\x01\n" +
	"\x12LatestDataResponse\x12<\n" +
	"\x0einstalled_apps\x18\x01 \x01(\v2\x15.server.InstalledAppsR\rinstalledApps\x120\n" +
	"\n" +
	"os_version\x18\x02 \x01(\v2\x11.server.OSVersionR\tosVersion\x12?\n" +
	"\x0fosquery_version\x18\x03 \x01(\v2\x16.server.OSQueryVersionR\x0eosqueryVersion*V\n" +
	"\x0eDeviceDataType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eINSTALLED_APPS\x10\x01\x12\x0e\n" +
	"\n" +
	"OS_VERSION\x10\x02\x12\x13\n" +
	"\x0fOSQUERY_VERSION\x10\x032\x80\x03\n" +
	"\x12NightsWatchService\x12T\n" +
	"\bRegister\x12\x17.server.RegisterRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/register\x12K\n" +
	"\x05Login\x12\x14.server.LoginRequest\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12_\n" +
	"\x0eSendDeviceData\x12\x19.server.DeviceDataRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/device/data\x12f\n" +
	"\n" +
	"LatestData\x12\x19.server.LatestDataRequest\x1a\x1a.server.LatestDataResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/device/data/{user_id}B3Z1github.com/nightswatchprotobufs/gogenproto/serverb\x06proto3"

var (
	file_protos_server_server_proto_rawDescOnce sync.Once
	file_protos_server_server_proto_rawDescData []byte
)

func file_protos_server_server_proto_rawDescGZIP() []byte {
	file_protos_server_server_proto_rawDescOnce.Do(func() {
		file_protos_server_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_server_server_proto_rawDesc), len(file_protos_server_server_proto_rawDesc)))
	})
	return file_protos_server_server_proto_rawDescData
}

var file_protos_server_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_server_server_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_server_server_proto_goTypes = []any{
	(DeviceDataType)(0),        // 0: server.DeviceDataType
	(*RegisterRequest)(nil),    // 1: server.RegisterRequest
	(*LoginRequest)(nil),       // 2: server.LoginRequest
	(*InstalledApps)(nil),      // 3: server.InstalledApps
	(*OSVersion)(nil),          // 4: server.OSVersion
	(*OSQueryVersion)(nil),     // 5: server.OSQueryVersion
	(*DeviceDataRequest)(nil),  // 6: server.DeviceDataRequest
	(*LatestDataRequest)(nil),  // 7: server.LatestDataRequest
	(*LatestDataResponse)(nil), // 8: server.LatestDataResponse
	(*InstalledApps_App)(nil),  // 9: server.InstalledApps.App
	(*emptypb.Empty)(nil),      // 10: google.protobuf.Empty
}
var file_protos_server_server_proto_depIdxs = []int32{
	9,  // 0: server.InstalledApps.apps:type_name -> server.InstalledApps.App
	0,  // 1: server.DeviceDataRequest.data_request_type:type_name -> server.DeviceDataType
	3,  // 2: server.DeviceDataRequest.installed_apps:type_name -> server.InstalledApps
	4,  // 3: server.DeviceDataRequest.os_version:type_name -> server.OSVersion
	5,  // 4: server.DeviceDataRequest.osquery_version:type_name -> server.OSQueryVersion
	0,  // 5: server.LatestDataRequest.data_request_types:type_name -> server.DeviceDataType
	3,  // 6: server.LatestDataResponse.installed_apps:type_name -> server.InstalledApps
	4,  // 7: server.LatestDataResponse.os_version:type_name -> server.OSVersion
	5,  // 8: server.LatestDataResponse.osquery_version:type_name -> server.OSQueryVersion
	1,  // 9: server.NightsWatchService.Register:input_type -> server.RegisterRequest
	2,  // 10: server.NightsWatchService.Login:input_type -> server.LoginRequest
	6,  // 11: server.NightsWatchService.SendDeviceData:input_type -> server.DeviceDataRequest
	7,  // 12: server.NightsWatchService.LatestData:input_type -> server.LatestDataRequest
	10, // 13: server.NightsWatchService.Register:output_type -> google.protobuf.Empty
	10, // 14: server.NightsWatchService.Login:output_type -> google.protobuf.Empty
	10, // 15: server.NightsWatchService.SendDeviceData:output_type -> google.protobuf.Empty
	8,  // 16: server.NightsWatchService.LatestData:output_type -> server.LatestDataResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_protos_server_server_proto_init() }
func file_protos_server_server_proto_init() {
	if File_protos_server_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_server_server_proto_rawDesc), len(file_protos_server_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_server_server_proto_goTypes,
		DependencyIndexes: file_protos_server_server_proto_depIdxs,
		EnumInfos:         file_protos_server_server_proto_enumTypes,
		MessageInfos:      file_protos_server_server_proto_msgTypes,
	}.Build()
	File_protos_server_server_proto = out.File
	file_protos_server_server_proto_goTypes = nil
	file_protos_server_server_proto_depIdxs = nil
}
